# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 */5 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Check files
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: execute py script # run miner
        env:
          STREAMERS: ${{ secrets.STREAMERS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER: ${{ secrets.SERVER }}
          PERSISTENT: ${{ secrets.PERSISTENT }}
          AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
        run: |
          python3 main.py
  
  second:
    runs-on: ubuntu-latest

    steps:
      - name: Check files
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: execute py script # run miner
        env:
          STREAMERS: ${{ secrets.STREAMERS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.SECOND_USERNAME }}
          SERVER: ${{ secrets.SERVER }}
          PERSISTENT: ${{ secrets.SECOND_PERSISTENT }}
          AUTHTOKEN: ${{ secrets.SECOND_AUTHTOKEN }}
        run: |
          python3 main.py
          
  third:

    runs-on: ubuntu-latest

    steps:
      - name: Check files
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: execute py script # run miner
        env:
          STREAMERS: ${{ secrets.STREAMERS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.THIRD_USERNAME }}
          SERVER: ${{ secrets.SERVER }}
          PERSISTENT: ${{ secrets.THIRD_PERSISTENT }}
          AUTHTOKEN: ${{ secrets.THIRD_AUTHTOKEN }}
        run: |
          python3 main.py
          
  fourth:

    runs-on: ubuntu-latest

    steps:
      - name: Check files
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: execute py script # run miner
        env:
          STREAMERS: ${{ secrets.STREAMERS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.FOURTH_USERNAME }}
          SERVER: ${{ secrets.SERVER }}
          PERSISTENT: ${{ secrets.FOURTH_PERSISTENT }}
          AUTHTOKEN: ${{ secrets.FOURTH_AUTHTOKEN }}
        run: |
          python3 main.py
          
